CREATE TABLE TARJETA(
	NUMERO VARCHAR(16) PRIMARY KEY,
	RUT_USUARIO VARCHAR(15) NOT NULL,
	CVV INT NOT NULL,
	NOMBRE_TITULAR TEXT,
	FOREIGN KEY (RUT_USUARIO) REFERENCES USUARIO(RUT)
);


CREATE TABLE COMPRA(
 ID_COMPRA INT PRIMARY KEY,
 RUT_USUARIO VARCHAR(15) NOT NULL,
 MONTO INT NOT NULL,
 FOREIGN KEY (RUT_USUARIO) REFERENCES USUARIO(RUT)
 
);

CREATE TABLE FACTURA(
	ID_FACTURA INT PRIMARY KEY,
	COMPRA INT NOT NULL,
	RUT_USUARIO VARCHAR(15) NOT NULL,
	FECHA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	MONTO_TOTAL INT NOT NULL,
	ESTADO TEXT NOT NULL,
	FOREIGN KEY (COMPRA) REFERENCES COMPRA(ID_COMPRA),
	FOREIGN KEY (RUT_USUARIO) REFERENCES USUARIO(RUT)
	
);

CREATE TABLE ECOMMERCE(
	ID_E INT PRIMARY KEY,
	COMPRA INT NOT NULL,
	NOMBRE VARCHAR(20) NOT NULL,
	FOREIGN KEY (COMPRA) REFERENCES COMPRA(ID_COMPRA)
);

CREATE TABLE CARRITO(
	ID_CARRO INT PRIMARY KEY,
	RUT_USUARIO VARCHAR(15) NOT NULL,
	FECHA_USO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (RUT_USUARIO) REFERENCES USUARIO(RUT)
);

CREATE TABLE PRODUCTO(
	ID_PRODUCTO INT PRIMARY KEY,
	ID_COMMERCE INT NOT NULL,
	TIPO TEXT NOT NULL,
	MARCA VARCHAR(20) NOT NULL,
	STOCK INT NOT NULL,
	PRECIO INT NOT NULL,
	FOREIGN KEY (ID_COMMERCE) REFERENCES ECOMMERCE(ID_E)
);

CREATE TABLE ITEM(
	ID_ITEM INT PRIMARY KEY,
	ID_CARRITO INT NOT NULL,
	ID_PROD INT NOT NULL,
	CAPACIDAD INT NOT NULL,
	FOREIGN KEY (ID_PROD) REFERENCES PRODUCTO(ID_PRODUCTO),
	FOREIGN KEY (ID_CARRITO) REFERENCES CARRITO(ID_CARRO)
);

CREATE TABLE CAMISETAS(
	ID_PRODUCTO INT PRIMARY KEY REFERENCES PRODUCTO(ID_PRODUCTO),
	NUMERO INT NOT NULL,
	TALLA VARCHAR(6) NOT NULL,
	EQUIPO VARCHAR(30) NOT NULL
);

CREATE TABLE SHORTS(
	ID_PRODUCTO INT PRIMARY KEY REFERENCES PRODUCTO(ID_PRODUCTO),
	TALLA VARCHAR(6) NOT NULL,
	EQUIPO VARCHAR(30) NOT NULL
	
);

CREATE TABLE ZAPATILLAS(
	ID_PRODUCTO INT PRIMARY KEY REFERENCES PRODUCTO(ID_PRODUCTO),
	MODELO VARCHAR(35) NOT NULL,
	TALLA FLOAT NOT NULL
);

INSERT INTO TARJETA(NUMERO,RUT_USUARIO,CVV,NOMBRE_TITULAR)
VALUES(123412341234,'12345678-9',123,'Usuario');

INSERT INTO CARRITO(ID_CARRO,RUT_USUARIO)
VALUES(1,'12345678-9');

INSERT INTO COMPRA(ID_COMPRA,RUT_USUARIO,MONTO)
VALUES(1,'12345678-9',10000);

INSERT INTO ECOMMERCE(ID_E,COMPRA,NOMBRE)
VALUES(777,1,'PARGAS');

INSERT INTO FACTURA(ID_FACTURA,COMPRA,RUT_USUARIO,MONTO_TOTAL,ESTADO)
VALUES(1,1,'12345678-9',10000,'PAGADO');

INSERT INTO PRODUCTO(ID_PRODUCTO,ID_COMMERCE,TIPO,MARCA,STOCK,PRECIO)
VALUES(1,777,'CAMISETA','NIKE',50,50000),
	  (2,777,'SHORT','ADIDAS',25,30000),
	  (3,777,'ZAPATILLA','PUMA',15,42000);

INSERT INTO CAMISETAS(ID_PRODUCTO,NUMERO,TALLA,EQUIPO)
VALUES(1,10,'L','REAL MADRID');

INSERT INTO SHORTS(ID_PRODUCTO,TALLA,EQUIPO)
VALUES(2,'M','COLO-COLO');

INSERT INTO ZAPATILLAS(ID_PRODUCTO,MODELO,TALLA)
VALUES(3,'MERCURIAL',42);

INSERT INTO ITEM(ID_ITEM,ID_CARRITO,ID_PROD,CAPACIDAD)
VALUES(1,1,2,5);



